[".config/fish/themes/Catppuccin Latte.theme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Latte.theme"
refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Latte.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Latte.tmTheme"
refreshPeriod = "168h"

[".local/bin/icat"]
type = "file"
url = "https://raw.githubusercontent.com/nekowinston/icat/main/icat.sh"
refreshPeriod = "168h"
executable = true
