[".config/fish/themes/Catppuccin Mocha.theme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Mocha.theme"
refreshPeriod = "24h"

[".config/fish/themes/Catppuccin Latte.theme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Latte.theme"
refreshPeriod = "24h"

[".config/btop/themes/catppuccin_mocha.theme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/btop/main/catppuccin_mocha.theme"
refreshPeriod = "24h"

{{- if ne .chezmoi.os "linux" }}
# exclude linux-specific externals

{{- end }}
