[".config/fish/themes/Catppuccin Mocha.theme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/fish/main/themes/Catppuccin%20Mocha.theme"
refreshPeriod = "24h"

[".config/bat/themes/Catppuccin-mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-mocha.tmTheme"
refreshPeriod = "24h"

[".config/btop/themes/catppuccin_mocha.theme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/btop/main/catppuccin_mocha.theme"
refreshPeriod = "24h"

{{- if ne .chezmoi.os "linux" }}
# exclude linux-specific externals

[".config/ulauncher/user-themes/Catppuccin-Mocha"]
type = "archive"
url = "https://github.com/catppuccin/ulauncher/archive/refs/heads/main.zip"
exact = true
stripComponents = 3
include = ["ulauncher-main/src/Catppuccin-Mocha/*"]
refreshPeriod = "24h"

[".local/share/icons/Catppuccin-Mocha-Green-Cursors"]
type = "archive"
url = "https://github.com/catppuccin/cursors/raw/main/cursors/Catppuccin-Mocha-Green-Cursors.zip"
exact = true
stripComponents = 1
refreshPeriod = "24h"

{{- end }}
