#! /usr/bin/env sh

set -eufx

cd "$HOME"

yadm submodule update --recursive --init

if [ ! -z $(which python) ]; then
    pyenv rehash
    python -m pip install --user --upgrade -r ~/.pip-packages
fi

if [ ! -f ~/.config/fish/completions/kubectl.fish ]; then
    mkdir -p ~/.config/fish/completions
    wget https://raw.githubusercontent.com/evanlucas/fish-kubectl-completions/master/completions/kubectl.fish -O ~/.config/fish/completions/kubectl.fish
fi
