theme = "kaolin-dark"

[editor]
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
cursorline = true
idle-timeout = 50
line-number = "relative"
rulers = [88, 120]
shell = ["fish", "-c"]
true-color = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
