[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.allFeatures = true

[language-server.lua-language-server.config.Lua.format]
enable = true
[language-server.lua-language-server.config.Lua.format.defaultConfig]
indent_style = "space"
indent_size = "4" 

[[language]]
name = "lua"
auto-format = true
